title: "Portafolio de Programación"
description: "Tarea de Teoría de la Programación."
theme: jekyll-theme-tactile
# Información personal
author: "Jefferson Sarango"

# Personalización del tema
show_excerpts: true
minima:
  skin: dark  # Cambia el estilo: opciones: classic, dark, auto, solarized-light, solarized-dark
  date_format: "%d %B %Y"


# Configuración básica
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
